### ISSUE TITLE
PyQt5 5.9 - Failed to create XCB context on travis

### ISSUE THREAD

**Issue by djhoese** [conda-forge/pyqt-feedstock#52] opened 2019-05-10 15:47 UTC
Vispy (CC @kmuehlbauer @larsoner) uses PyQt5 to run its examples/tests on travis. The jobs now fail starting with PyQt 5.9 with the message:

```
xkbcommon: ERROR: failed to add default include path 
WARNING: Qt: Failed to create XKB context!
WARNING: Use QT_XKB_CONFIG_ROOT environmental variable to provide an additional search path, add ':' as separator to provide several search paths and/or make sure that XKB configuration data directory contains recent enough contents, to update please see http://cgit.freedesktop.org/xkeyboard-config/ .
```

See https://travis-ci.org/vispy/vispy/jobs/530796417 for the full job. See https://travis-ci.org/vispy/vispy/jobs/529293572 for a passing job using PyQt5 5.6.

Any ideas what may have changed in the build process? Maybe this environment variable is set in an activation script now? I'm not sure we are reactivating the environment after we install PyQt5 and we may be using an older version of conda (via astropy's ci-helpers).

**Comment by ccordoba12** [comment] 2019-05-11 08:42
Perhaps you need to install an additional system package in Travis now. Please see

https://github.com/conda-forge/pyqt-feedstock/blob/master/recipe/yum_requirements.txt

for the system packages required to import all PyQt5 modules now (those are for CentOS 6).

**Comment by djhoese** [comment] 2019-05-11 14:05
We had similar issues with the recent SDL2 build: https://github.com/conda-forge/sdl2-feedstock/issues/13

I'll try to compare the yum and apt packages and see if that helps at all.

**Comment by kmuehlbauer** [comment] 2019-05-11 15:48
@djhoese @ccordoba12 In the latest build log of PyQt5.9 this shows up:

```
+ xvfb-run -a bash -c 'python pyqt_test.py'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-conda'
xkbcommon: ERROR: failed to add default include path 
Qt: Failed to create XKB context!
Use QT_XKB_CONFIG_ROOT environmental variable to provide an additional search path, add ':' as separator to provide several search paths and/or make sure that XKB configuration data directory contains recent enough contents, to update please see http://cgit.freedesktop.org/xkeyboard-config/ .
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 0, greenBufferSize 0, blueBufferSize 0, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(SingleBuffer), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Falling back to using screens root_visual.
Unsupported screen format: depth: 8, red_mask: 0, blue_mask: 0
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::setCompositionMode: Painter not active
+ exit 0
```
Here is the link to the azure builds (unfortunately I've no idea how to link into the log itself):
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=33234&view=logs

**Comment by djhoese** [comment] 2019-05-11 15:54
So that would suggest that the test script isn't properly testing things then. At least that's how I read that. I wonder how PyQt can have all of those errors and not raise some exception.

**Comment by kmuehlbauer** [comment] 2019-05-11 15:58
I've no idea if other packages beside `vispy` are affected as well, but if, the :hankey: will hit the fan soon. :grimacing:

**Comment by djhoese** [comment] 2019-05-11 16:01
There is also this old build of the Qt library (qt-feedstock):

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=30715

```
  X11:
    Using system-provided XCB libraries .. no
    EGL on X11 ........................... yes
    Xinput2 .............................. yes
    XCB XKB .............................. yes
    XLib ................................. yes
    XCB render ........................... yes
    XCB GLX .............................. yes
    XCB Xlib ............................. yes
    Using system-provided xkbcommon ...... no
```

No idea if xkbcommon should be 'yes' but just pointing out what I'm seeing.

**Comment by kmuehlbauer** [comment] 2019-05-13 11:10
@djhoese There are currently no green linux builds on azure for `qt`. See also [this comment](https://github.com/conda-forge/qt-feedstock/pull/102#issuecomment-486155568).

Ping @ocefpaf Something might be wrong with the current `qt 5.9.7` related to the issues seen here. WIthout the logs we can't say much. Do you have any thoughts? Should we open an issue at `qt-feedstock`?

**Comment by hmaarrfk** [comment] 2019-05-13 11:39
On my own linux machine, it seems to be related to the new qt packages on conda-forge, I had to export the following runtime variables

bash:
```bash
export QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb
```

xonsh
```
$QT_XKB_CONFIG_ROOT="/usr/share/X11/xkb"
```

**Comment by hmaarrfk** [comment] 2019-05-13 11:42
xref https://stackoverflow.com/questions/26974644/no-keyboard-input-in-qt-creator-after-update-to-qt5

**Comment by ocefpaf** [comment] 2019-05-13 12:29
> Ping @ocefpaf Something might be wrong with the current `qt 5.9.7` related to the issues seen here. WIthout the logs we can't say much. Do you have any thoughts? Should we open an issue at `qt-feedstock`?

Sadly `qt` does not build on the CIs and those were local builds uploaded to the channel.

**Comment by kmuehlbauer** [comment] 2019-05-13 12:40
@ocefpaf Yes, no problem. But how would we tackle this in the best way? Could we add this variable to the `qt-feedstock` somehow that it get's activated if `qt` is installed?

**Comment by ocefpaf** [comment] 2019-05-13 12:41
> @ocefpaf Yes, no problem. But how would we tackle this in the best way? Could we add this variable to the `qt-feedstock` somehow that it get's activated if `qt` is installed?

I'm looking into it. To be honest I'm not sure what is the best solution here. Maybe @mingwandroid or @isuruf could comment on what they think is the best course of action.

**Comment by hmaarrfk** [comment] 2019-05-13 12:57
@ocefpaf I thought there were a few super secret machines that you all had setup for when timeouts happen on Azure? Did those time out as well?

Finally, when building locally, don't you use the same container as the CIs?

**Comment by ocefpaf** [comment] 2019-05-13 13:02
> @ocefpaf I thought there were a few super secret machines that you all had setup for when timeouts happen on Azure? Did those time out as well?

Only for macOS and ironically that is the only one that worked without the dedicated machine :smile: 

> Finally, when building locally, don't you use the same container as the CIs?

For Linux? Yes. Window sis more complicated.

**Comment by hmaarrfk** [comment] 2019-05-13 13:14
Got it. Strange that Linux is giving this kind of issue in this case. Maybe it is bug upstream in qt then.

**Comment by ocefpaf** [comment] 2019-05-13 14:54
> Got it. Strange that Linux is giving this kind of issue in this case. Maybe it is bug upstream in qt then.

Or a problem with my build :grimacing: still looking into it but `qt` takes hours to build and test :frowning_face:

**Comment by grlee77** [comment] 2019-05-15 06:07
There are many things related to X11, etc. in `yum_requirements.txt` on the AnacondaRecipes qt-feedstock:
https://github.com/AnacondaRecipes/qt-feedstock/blob/master/recipe/yum_requirements.txt
that are not in the conda-forge variant:
https://github.com/conda-forge/qt-feedstock/blob/master/recipe/yum_requirements.txt

Perhaps that could be the source of the problem?  The following Qt 5.9 bug report also seems related:
https://bugreports.qt.io/browse/QTBUG-60005

**Comment by ocefpaf** [comment] 2019-05-15 09:36
> There are many things related to X11, etc. in `yum_requirements.txt` on the AnacondaRecipes qt-feedstock:
> [AnacondaRecipes/qt-feedstock:recipe/yum_requirements.txt@`master`](https://github.com/AnacondaRecipes/qt-feedstock/blob/master/recipe/yum_requirements.txt) [](/AnacondaRecipes/qt-feedstock/blob/HEAD@{2019-05-15T06:07:04Z}/recipe/yum_requirements.txt)
> that are not in the conda-forge variant:
> [conda-forge/qt-feedstock:recipe/yum_requirements.txt@`master`](https://github.com/conda-forge/qt-feedstock/blob/master/recipe/yum_requirements.txt) [](/conda-forge/qt-feedstock/blob/HEAD@{2019-05-15T06:07:04Z}/recipe/yum_requirements.txt)
> 
> Perhaps that could be the source of the problem? The following Qt 5.9 bug report also seems related:
> [bugreports.qt.io/browse/QTBUG-60005](https://bugreports.qt.io/browse/QTBUG-60005)

Nope. AnancondaRecipes does not use the `yum_requirements.txt` at all and that is the old `conda-forge` one.

**Comment by djhoese** [comment] 2019-05-19 14:29
@hmaarrfk Were you getting these errors/warnings on normal use on Ubuntu (X11)? Or did they only show up when doing things off screen (fake display like in the vispy tests)?

**Comment by hmaarrfk** [comment] 2019-05-19 14:32
Local. Seems like I'm running X11, not Wayland too

```
$ loginctl show-session 2 -p Type                                                                       
Type=x11
```

**Comment by djhoese** [comment] 2019-05-19 14:41
So that would mean this is an issue for anyone using this new build on a Linux X11 machine?

**Comment by hmaarrfk** [comment] 2019-05-19 14:41
maybe, want me to try and create a new user?

**Comment by djhoese** [comment] 2019-05-19 14:44
If you have the time. Any new data points I'm sure would help. I'm guessing that using the Qt backend for matplotlib should also produce these errors/warnings. That would make this a bigger deal than our little ol' vispy library.

**Comment by hmaarrfk** [comment] 2019-05-19 14:55
ok, i just created a new user, add rebooted into it. 

Defaults works fine.

Creating two environments, one with defaults, one with conda forge and installing spyder
```
conda install spyder [-c conda-forge]
```
The one for conda-forge goes back QT 5.6 since spyder 3.3.4 doesn't seem to be built for qt????
https://github.com/conda-forge/spyder-feedstock/pull/52

For some reason, if you force qt 5.9
```
conda install spyder qt=5.9 -c conda-forge
```
you will get

spyder 3.3.1 and python 3.6

Anyway, the issue definitely persists with that combination


<details> <summary>Solved package list for spyder and qt=5.9 on conda-forge</summary>

This was done on my hacked up user, but from what I recall, the same version of python, qt, and spyder were installed on a fresh user.

```
(forge) mark2@xps ~                                                                                     
$ conda install spyder qt=5.9                                                                           
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /home/mark2/miniconda3/envs/forge

  added / updated specs:
    - qt=5.9
    - spyder


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    astroid-2.2.5              |           py36_0         268 KB  conda-forge
    isort-4.3.20               |           py36_0          64 KB  conda-forge
    keyring-19.0.1             |           py36_0          48 KB  conda-forge
    lazy-object-proxy-1.4.1    |   py36h516909a_0          27 KB  conda-forge
    pylint-2.3.1               |           py36_0         822 KB  conda-forge
    qtconsole-4.4.4            |             py_0          84 KB  conda-forge
    spyder-3.3.1               |           py36_2         2.6 MB  conda-forge
    spyder-kernels-0.4.4       |           py36_0          64 KB  conda-forge
    typed-ast-1.3.5            |   py36h516909a_0         204 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         4.1 MB

The following NEW packages will be INSTALLED:

  alabaster          conda-forge/noarch::alabaster-0.7.12-py_0
  asn1crypto         conda-forge/linux-64::asn1crypto-0.24.0-py36_1003
  astroid            conda-forge/linux-64::astroid-2.2.5-py36_0
  attrs              conda-forge/noarch::attrs-19.1.0-py_0
  babel              conda-forge/noarch::babel-2.6.0-py_1
  backcall           conda-forge/noarch::backcall-0.1.0-py_0
  bleach             conda-forge/noarch::bleach-3.1.0-py_0
  ca-certificates    conda-forge/linux-64::ca-certificates-2019.3.9-hecc5488_0
  certifi            conda-forge/linux-64::certifi-2019.3.9-py36_0
  cffi               conda-forge/linux-64::cffi-1.12.3-py36h8022711_0
  chardet            conda-forge/linux-64::chardet-3.0.4-py36_1003
  cloudpickle        conda-forge/noarch::cloudpickle-1.0.0-py_0
  cryptography       conda-forge/linux-64::cryptography-2.6.1-py36h72c5cf5_0
  dbus               conda-forge/linux-64::dbus-1.13.6-he372182_0
  decorator          conda-forge/noarch::decorator-4.4.0-py_0
  defusedxml         conda-forge/noarch::defusedxml-0.5.0-py_1
  docutils           conda-forge/linux-64::docutils-0.14-py36_1001
  entrypoints        conda-forge/linux-64::entrypoints-0.3-py36_1000
  expat              conda-forge/linux-64::expat-2.2.5-hf484d3e_1002
  fontconfig         conda-forge/linux-64::fontconfig-2.13.1-he4413a7_1000
  freetype           conda-forge/linux-64::freetype-2.10.0-he983fc9_0
  gettext            conda-forge/linux-64::gettext-0.19.8.1-hc5be6a0_1002
  glib               conda-forge/linux-64::glib-2.58.3-hf63aee3_1001
  gst-plugins-base   conda-forge/linux-64::gst-plugins-base-1.14.4-hdf3bae2_1001
  gstreamer          conda-forge/linux-64::gstreamer-1.14.4-h66beb1c_1001
  icu                conda-forge/linux-64::icu-58.2-hf484d3e_1000
  idna               conda-forge/linux-64::idna-2.8-py36_1000
  imagesize          conda-forge/noarch::imagesize-1.1.0-py_0
  ipykernel          conda-forge/linux-64::ipykernel-5.1.1-py36h24bf2e0_0
  ipython            conda-forge/linux-64::ipython-7.5.0-py36h24bf2e0_0
  ipython_genutils   conda-forge/noarch::ipython_genutils-0.2.0-py_1
  isort              conda-forge/linux-64::isort-4.3.20-py36_0
  jedi               conda-forge/linux-64::jedi-0.13.3-py36_0
  jeepney            conda-forge/noarch::jeepney-0.4-py_0
  jinja2             conda-forge/noarch::jinja2-2.10.1-py_0
  jpeg               conda-forge/linux-64::jpeg-9c-h14c3975_1001
  jsonschema         conda-forge/linux-64::jsonschema-3.0.1-py36_0
  jupyter_client     conda-forge/noarch::jupyter_client-5.2.4-py_3
  jupyter_core       conda-forge/noarch::jupyter_core-4.4.0-py_0
  keyring            conda-forge/linux-64::keyring-19.0.1-py36_0
  lazy-object-proxy  conda-forge/linux-64::lazy-object-proxy-1.4.1-py36h516909a_0
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1006
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-8.2.0-hdf63c60_1
  libiconv           conda-forge/linux-64::libiconv-1.15-h516909a_1005
  libpng             conda-forge/linux-64::libpng-1.6.37-hed695b0_0
  libsodium          conda-forge/linux-64::libsodium-1.0.16-h14c3975_1001
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-8.2.0-hdf63c60_1
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h14c3975_1000
  libxcb             conda-forge/linux-64::libxcb-1.13-h14c3975_1002
  libxml2            conda-forge/linux-64::libxml2-2.9.9-h13577e0_0
  markupsafe         conda-forge/linux-64::markupsafe-1.1.1-py36h14c3975_0
  mccabe             conda-forge/noarch::mccabe-0.6.1-py_1
  mistune            conda-forge/linux-64::mistune-0.8.4-py36h14c3975_1000
  nbconvert          conda-forge/noarch::nbconvert-5.5.0-py_0
  nbformat           conda-forge/noarch::nbformat-4.4.0-py_1
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  numpydoc           conda-forge/noarch::numpydoc-0.9.1-py_0
  openssl            conda-forge/linux-64::openssl-1.1.1b-h14c3975_1
  packaging          conda-forge/noarch::packaging-19.0-py_0
  pandoc             conda-forge/linux-64::pandoc-2.7.2-0
  pandocfilters      conda-forge/noarch::pandocfilters-1.4.2-py_1
  parso              conda-forge/noarch::parso-0.4.0-py_0
  pcre               conda-forge/linux-64::pcre-8.41-hf484d3e_1003
  pexpect            conda-forge/linux-64::pexpect-4.7.0-py36_0
  pickleshare        conda-forge/linux-64::pickleshare-0.7.5-py36_1000
  pip                conda-forge/linux-64::pip-19.1-py36_0
  prompt_toolkit     conda-forge/noarch::prompt_toolkit-2.0.9-py_0
  psutil             conda-forge/linux-64::psutil-5.6.2-py36h516909a_0
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h14c3975_1001
  ptyprocess         conda-forge/noarch::ptyprocess-0.6.0-py_1001
  pycodestyle        conda-forge/noarch::pycodestyle-2.5.0-py_0
  pycparser          conda-forge/linux-64::pycparser-2.19-py36_1
  pyflakes           conda-forge/noarch::pyflakes-2.1.1-py_0
  pygments           conda-forge/noarch::pygments-2.4.0-py_0
  pylint             conda-forge/linux-64::pylint-2.3.1-py36_0
  pyopenssl          conda-forge/linux-64::pyopenssl-19.0.0-py36_0
  pyparsing          conda-forge/noarch::pyparsing-2.4.0-py_0
  pyqt               conda-forge/linux-64::pyqt-5.9.2-py36hcca6a23_0
  pyrsistent         conda-forge/linux-64::pyrsistent-0.15.2-py36h516909a_0
  pysocks            conda-forge/linux-64::pysocks-1.7.0-py36_0
  python             conda-forge/linux-64::python-3.6.7-h381d211_1004
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.0-py_0
  pytz               conda-forge/noarch::pytz-2019.1-py_0
  pyzmq              conda-forge/linux-64::pyzmq-18.0.1-py36hc4ba49a_1
  qt                 conda-forge/linux-64::qt-5.9.7-h52cfd70_1
  qtawesome          conda-forge/noarch::qtawesome-0.5.7-pyh8a2030e_0
  qtconsole          conda-forge/noarch::qtconsole-4.4.4-py_0
  qtpy               conda-forge/noarch::qtpy-1.7.1-pyhde82777_0
  readline           conda-forge/linux-64::readline-7.0-hf8c457e_1001
  requests           conda-forge/linux-64::requests-2.22.0-py36_0
  rope               conda-forge/noarch::rope-0.14.0-py_0
  secretstorage      conda-forge/linux-64::secretstorage-3.1.1-py36_0
  setuptools         conda-forge/linux-64::setuptools-41.0.1-py36_0
  sip                conda-forge/linux-64::sip-4.19.8-py36hf484d3e_1000
  six                conda-forge/linux-64::six-1.12.0-py36_1000
  snowballstemmer    conda-forge/noarch::snowballstemmer-1.2.1-py_1
  sphinx             conda-forge/noarch::sphinx-2.0.1-py_0
  sphinxcontrib-app~ conda-forge/noarch::sphinxcontrib-applehelp-1.0.1-py_0
  sphinxcontrib-dev~ conda-forge/noarch::sphinxcontrib-devhelp-1.0.1-py_0
  sphinxcontrib-htm~ conda-forge/noarch::sphinxcontrib-htmlhelp-1.0.2-py_0
  sphinxcontrib-jsm~ conda-forge/noarch::sphinxcontrib-jsmath-1.0.1-py_0
  sphinxcontrib-qth~ conda-forge/noarch::sphinxcontrib-qthelp-1.0.2-py_0
  sphinxcontrib-ser~ conda-forge/noarch::sphinxcontrib-serializinghtml-1.1.1-py_0
  spyder             conda-forge/linux-64::spyder-3.3.1-py36_2
  spyder-kernels     conda-forge/linux-64::spyder-kernels-0.4.4-py36_0
  sqlite             conda-forge/linux-64::sqlite-3.26.0-h67949de_1001
  testpath           conda-forge/noarch::testpath-0.4.2-py_1001
  tk                 conda-forge/linux-64::tk-8.6.9-h84994c4_1001
  tornado            conda-forge/linux-64::tornado-6.0.2-py36h516909a_0
  traitlets          conda-forge/linux-64::traitlets-4.3.2-py36_1000
  typed-ast          conda-forge/linux-64::typed-ast-1.3.5-py36h516909a_0
  urllib3            conda-forge/linux-64::urllib3-1.24.3-py36_0
  wcwidth            conda-forge/noarch::wcwidth-0.1.7-py_1
  webencodings       conda-forge/noarch::webencodings-0.5.1-py_1
  wheel              conda-forge/linux-64::wheel-0.33.4-py36_0
  wrapt              conda-forge/linux-64::wrapt-1.11.1-py36h516909a_0
  wurlitzer          conda-forge/linux-64::wurlitzer-1.0.2-py36_1000
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.9-h14c3975_0
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.3-h516909a_0
  xz                 conda-forge/linux-64::xz-5.2.4-h14c3975_1001
  zeromq             conda-forge/linux-64::zeromq-4.3.1-hf484d3e_1000
  zlib               conda-forge/linux-64::zlib-1.2.11-h14c3975_1004


Proceed ([y]/n)? 

```

</details>

**Comment by djhoese** [comment] 2019-05-19 14:58
If you use Qt 5.9 and create/show a matplotlib figure with the Qt backend does it show these errors?

**Comment by hmaarrfk** [comment] 2019-05-19 15:02
Yeah

![image](https://user-images.githubusercontent.com/90008/57984035-8aa5a180-7a25-11e9-8866-47b4ed5c7b2a.png)

**Comment by hmaarrfk** [comment] 2019-05-19 15:02
i can't type in that little window.

**Comment by djhoese** [comment] 2019-05-19 15:03
@ocefpaf @ccordoba12 Given the above results, what are your thoughts on marking the current Qt 5.9 as a broken build for linux?

**Comment by hmaarrfk** [comment] 2019-05-19 15:11
It could be that we specify 

```
                -qt-xcb \
                -qt-xkbcommon \
-xkb-config-root $PREFIX/lib \
```
xkb config root is specified, but we are using CDTs???

**Comment by ocefpaf** [comment] 2019-05-19 15:32
> @ocefpaf @ccordoba12 Given the above results, what are your thoughts on marking the current Qt 5.9 as a broken build for linux?

I asked a few people who know about this them me and no answer. I'll ping them again. They are not completely broken though, looks like they are working for some applications.

> xkb config root is specified, but we are using CDTs???

@mingwandroid any advice for us here?

**Comment by hmaarrfk** [comment] 2019-05-19 15:41
Defaults uses the same flags
https://github.com/AnacondaRecipes/qt-feedstock/blob/master/recipe/build.sh#L141

so thats not it

**Comment by ccordoba12** [comment] 2019-05-19 15:50
This definitely requires a Qt rebuild on Linux (but probably not a PyQt one). I think the problem is that the RPM package for xkbcommon (no idea what that is) is not installed in the docker image used by conda-forge, whereas Anaconda complies packages in an image or VM that has all X11 components installed.

@ocefpaf, you can try adding that package to yum_requirements in the Qt repo and recompiling again. I know that's expensive but that's the only solution I see at the moment.

**Comment by ocefpaf** [comment] 2019-05-19 16:01
> Defaults uses the same flags
> [AnacondaRecipes/qt-feedstock:recipe/build.sh@`master`#L141](https://github.com/AnacondaRecipes/qt-feedstock/blob/master/recipe/build.sh#L141) [](/AnacondaRecipes/qt-feedstock/blob/HEAD@{2019-05-19T15:41:33Z}/recipe/build.sh#L141)
> 
> so thats not it

@hmaarrfk the recipe is the same from `defaults`. So the differences is in our build systems.

> I think the problem is that the RPM package for xkbcommon (no idea what that is) is not installed in the docker image used by conda-forge, whereas Anaconda complies packages in an image or VM that has all X11 components installed.

We install with `yum`:

```
chrpath
mesa-libGL
ruby
```

all listed in the `yum_requirements.txt`.


>  whereas Anaconda complies packages in an image or VM that has all X11 components installed.

I thought that AnacondaRecipes relied only on CTDs. If that is true then it would be nice to get a list of the X11 stuff installed to create a similar build.

**Comment by hmaarrfk** [comment] 2019-05-19 16:01
Good find. It does seem that from a commit message https://github.com/conda-forge/qt-feedstock/commit/63dbab69be4848aeaf6687619d03eeae1209546b#diff-cd6a7861c185736da828f5fa163c4806

that installing things in the yum_requirements was removed in favour of the conda-forge packages.

But when the recipe was merged in from AD (I'm guess that is what happened), the yum_requirements.txt wasn't pulled in

https://github.com/AnacondaRecipes/qt-feedstock/blob/master/recipe/yum_requirements.txt

expensive, but likely the fix!

**Comment by hmaarrfk** [comment] 2019-05-19 16:02
@ocefpaf, from their yum_requirements file they seem to install
```
libX11-devel
libXt-devel
libXext-devel
chrpath
libXrender-devel
gtk2-devel
dbus-devel
libSM-devel
libICE-devel
xorg-x11-server-Xvfb
ruby
```

maybe those are the missing packages?

**Comment by ocefpaf** [comment] 2019-05-19 16:03
> Good find. It does seem that from a commit message [conda-forge/qt-feedstock@63dbab6#diff-cd6a7861c185736da828f5fa163c4806](https://github.com/conda-forge/qt-feedstock/commit/63dbab69be4848aeaf6687619d03eeae1209546b#diff-cd6a7861c185736da828f5fa163c4806)
> 
> that installing things in the yum_requirements was removed in favour of the conda-forge packages.
> 
> But when the recipe was merged in from AD (I'm guess that is what happened), the yum_requirements.txt wasn't pulled in
> 
> [AnacondaRecipes/qt-feedstock:recipe/yum_requirements.txt@`master`](https://github.com/AnacondaRecipes/qt-feedstock/blob/master/recipe/yum_requirements.txt) [](/AnacondaRecipes/qt-feedstock/blob/HEAD@{2019-05-19T16:01:02Z}/recipe/yum_requirements.txt)
> 
> expensive, but likely the fix!

@hmaarrfk I can try a build with that but my understanding was that the CTDs should cover that.

**Comment by ccordoba12** [comment] 2019-05-19 16:08
> I thought that AnacondaRecipes relied only on CTDs. If that is true then it would be nice to get a list of the X11 stuff installed to create a similar build.

I don't think the problem has to do with CDT's, just with the fact that Qt doesn't find where `xkbcommon` is installed in the system (because it's not installed), so you have to tell it that by setting `QT_XKB_CONFIG_ROOT`.

So my guess is that if it finds it in `/usr/share/X11/xkb`, it will use that as the default and the problem will go away.

**Comment by hmaarrfk** [comment] 2019-05-19 16:11
> So my guess is that if it finds it in /usr/share/X11/xkb, it will use that as the default and the problem will go away.

And we are hoping that is a common enough location on enough platforms?

**Comment by mingwandroid** [comment] 2019-05-19 16:13
It will depend on whether the test for xkb tries to run the test program or not. If it does then yes, yum_requirements.txt should be added to. If not then it doesn't matter. I'd general add them.

**Comment by ccordoba12** [comment] 2019-05-19 16:37
> And we are hoping that is a common enough location on enough platforms?

It should be on most Linux distros (I haven't heard anyone complain about this before).

**Comment by ocefpaf** [comment] 2019-05-24 13:58
I just uploaded a new package that should solved this. Please try it and report back.
(It may take ~30 min for the package to be available and it will be `qt 5.9.7 h52cfd70_2`.)

**Closed** 2019-05-24 14:13 UTC

**Comment by djhoese** [comment] 2019-05-24 15:00
@ocefpaf Should I expect to see it here: https://anaconda.org/conda-forge/qt/files?version=
I don't see anything yet and its been an hour.

**Comment by ocefpaf** [comment] 2019-05-24 15:10
We are having trouble with uploads. Ping @soapy.

**Comment by ocefpaf** [comment] 2019-05-24 15:21
I re-uploaded and this time it seems to be in the file list:

https://anaconda.org/conda-forge/qt/files

it should take ~20 min for it to be available for download.

**Comment by grlee77** [comment] 2019-05-24 15:36
I can confirm that the new version fixes the issue for me (on ubuntu 18.04). Thanks @ocefpaf!

**Comment by djhoese** [comment] 2019-05-24 16:02
Looks like it fixed vispy's travis tests too: https://travis-ci.org/vispy/vispy/jobs/535042985

🎉

**Comment by ocefpaf** [comment] 2019-05-24 16:27
Thanks @grlee77 and @djhoese for reporting back. Glad it is resolved!
